"""Спільні versioned контракти даних (IDs, temporal axes, artifacts, events); owner — WP-01C.

Чисті Pydantic v2 моделі без I/O (єдиний виняток — read-only loader
`docs/research/source-registry.yaml` для валідації `source_id`). Персистенція
(SQLAlchemy/PyMongo mapping) — WP-01A/01B; JSON Schema snapshots — `schemas/**`
(`uv run collector contracts export [--check]`). Процедура змін і ownership — `docs/contracts.md`.
"""

from __future__ import annotations

from collector.contracts._base import (
    ContractModel,
    JsonObject,
    SchemaVersion,
    VersionedDocument,
    parse_schema_version,
)
from collector.contracts.artifacts import (
    ArtifactRef,
    NormalizedArtifactRef,
    RawArtifactRef,
    UploadClaim,
    can_commit,
)
from collector.contracts.canonical import (
    CANONICAL_JSON_MEDIA_TYPE,
    CanonicalEncodingError,
    canonical_json_bytes,
    canonical_sha256,
    sha256_hex,
)
from collector.contracts.current import (
    CurrentDocumentBase,
    Lineage,
    SourceRef,
    compute_state_hash_v1,
)
from collector.contracts.enums import (
    STATE_AXES,
    ContactKind,
    ContentAccess,
    DataDomain,
    EffectiveAtBasis,
    EntityKind,
    EntityLifecycle,
    FetchOutcome,
    ObservationReason,
    ReleaseState,
    ResolutionAction,
    RouteState,
    SourceState,
    TimePrecision,
    UploadClaimStatus,
    map_research_access_state,
)
from collector.contracts.events import (
    DOMAIN_CHANGED_MEDIA_TYPE,
    EVENT_INLINE_LIMIT_BYTES,
    DomainChangedEvent,
    EncodedEvent,
    EventTooLargeError,
    decode_event,
    encode_event,
)
from collector.contracts.identity import (
    EntityId,
    IdentityHash,
    NormalizedUrl,
    Sha256Hex,
    SourceIdentity,
    Uuid7Generator,
    entity_id_timestamp,
    fetch_idempotency_key,
    identity_hash_v1,
    new_entity_id,
    planned_at_bucket,
    raw_object_key,
    translation_idempotency_key,
)
from collector.contracts.projection import (
    AppliedProjectionReceipt,
    ProjectionAcknowledgement,
    ProjectionCommand,
    should_emit_domain_changed,
)
from collector.contracts.release import (
    RELEASE_TRANSITIONS,
    ComponentVersions,
    EntityVersionRef,
    ReleaseManifest,
    ReleasePart,
    ReleaseTransitionError,
    ReleaseWatermark,
    SourceInclusion,
    can_transition,
    transition_release,
    validate_manifest_update,
)
from collector.contracts.resolution import (
    ResolutionDecision,
    ResolutionSnapshot,
    project_groups,
)
from collector.contracts.source_registry import (
    SourceRegistry,
    SourceRegistryError,
    known_source_ids,
    load_source_registry,
)
from collector.contracts.temporal import (
    BitemporalInterval,
    EffectiveTime,
    EntityTime,
    SourceTime,
    SystemTime,
    UtcDatetime,
    VersionInterval,
    VersionTimes,
    build_intervals,
    derive_effective_time,
)
from collector.contracts.values import (
    ContactValue,
    MeasuredValue,
    Money,
    normalize_contact,
    normalize_email,
    normalize_phone,
)

CONTRACTS_VERSION = "1.0"
"""Версія набору shared-контрактів (для `collector version` і release manifest)."""

__all__ = [
    "CANONICAL_JSON_MEDIA_TYPE",
    "CONTRACTS_VERSION",
    "DOMAIN_CHANGED_MEDIA_TYPE",
    "EVENT_INLINE_LIMIT_BYTES",
    "RELEASE_TRANSITIONS",
    "STATE_AXES",
    "AppliedProjectionReceipt",
    "ArtifactRef",
    "BitemporalInterval",
    "CanonicalEncodingError",
    "ComponentVersions",
    "ContactKind",
    "ContactValue",
    "ContentAccess",
    "ContractModel",
    "CurrentDocumentBase",
    "DataDomain",
    "DomainChangedEvent",
    "EffectiveAtBasis",
    "EffectiveTime",
    "EncodedEvent",
    "EntityId",
    "EntityKind",
    "EntityLifecycle",
    "EntityTime",
    "EntityVersionRef",
    "EventTooLargeError",
    "FetchOutcome",
    "IdentityHash",
    "JsonObject",
    "Lineage",
    "MeasuredValue",
    "Money",
    "NormalizedArtifactRef",
    "NormalizedUrl",
    "ObservationReason",
    "ProjectionAcknowledgement",
    "ProjectionCommand",
    "RawArtifactRef",
    "ReleaseManifest",
    "ReleasePart",
    "ReleaseState",
    "ReleaseTransitionError",
    "ReleaseWatermark",
    "ResolutionAction",
    "ResolutionDecision",
    "ResolutionSnapshot",
    "RouteState",
    "SchemaVersion",
    "Sha256Hex",
    "SourceIdentity",
    "SourceInclusion",
    "SourceRef",
    "SourceRegistry",
    "SourceRegistryError",
    "SourceState",
    "SourceTime",
    "SystemTime",
    "TimePrecision",
    "UploadClaim",
    "UploadClaimStatus",
    "UtcDatetime",
    "Uuid7Generator",
    "VersionInterval",
    "VersionTimes",
    "VersionedDocument",
    "build_intervals",
    "can_commit",
    "can_transition",
    "canonical_json_bytes",
    "canonical_sha256",
    "compute_state_hash_v1",
    "decode_event",
    "derive_effective_time",
    "encode_event",
    "entity_id_timestamp",
    "fetch_idempotency_key",
    "identity_hash_v1",
    "known_source_ids",
    "load_source_registry",
    "map_research_access_state",
    "new_entity_id",
    "normalize_contact",
    "normalize_email",
    "normalize_phone",
    "parse_schema_version",
    "planned_at_bucket",
    "project_groups",
    "raw_object_key",
    "sha256_hex",
    "should_emit_domain_changed",
    "transition_release",
    "translation_idempotency_key",
    "validate_manifest_update",
]
