"""Програмний Alembic для CLI `collector db migrate` та integration-тестів.

`alembic.ini`/`migrations/postgres` живуть у корені репозиторію (картка WP-01A), а не в
пакеті, тому шлях шукається: env `COLLECTOR_ALEMBIC_INI` → вгору від cwd → вгору від файлу
пакета (editable install / Docker image з копією репозиторію).

Transaction boundary: `upgrade_to_head(conn)` виконує міграції у транзакції переданого
`AsyncConnection` (Alembic env використовує спільне з'єднання, `env.py`); `alembic check`
(`check_no_drift`) — read-only.
"""

from __future__ import annotations

import os
from collections.abc import Callable
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected, CommandError
from sqlalchemy import Connection
from sqlalchemy.ext.asyncio import AsyncConnection

ALEMBIC_INI_ENV = "COLLECTOR_ALEMBIC_INI"


class MigrationsNotFoundError(FileNotFoundError):
    """Не знайдено `alembic.ini`."""


def find_alembic_ini(start: Path | None = None) -> Path:
    """`COLLECTOR_ALEMBIC_INI` або перший `alembic.ini` вгору від `start`/cwd/пакета."""
    override = os.environ.get(ALEMBIC_INI_ENV)
    if override:
        path = Path(override)
        if path.is_file():
            return path
        msg = f"{ALEMBIC_INI_ENV}={override!r}: файл не знайдено"
        raise MigrationsNotFoundError(msg)
    roots = [start or Path.cwd(), Path(__file__).resolve()]
    for root in roots:
        for candidate in (root, *root.parents):
            ini = candidate / "alembic.ini"
            if ini.is_file():
                return ini
    msg = "alembic.ini не знайдено (задайте COLLECTOR_ALEMBIC_INI)"
    raise MigrationsNotFoundError(msg)


def alembic_config(ini_path: Path | None = None) -> Config:
    ini = ini_path or find_alembic_ini()
    config = Config(str(ini))
    config.set_main_option("script_location", str(ini.parent / "migrations" / "postgres"))
    return config


def _run_with_connection(
    connection: Connection, action: Callable[[Config], None], ini_path: Path | None
) -> None:
    config = alembic_config(ini_path)
    config.attributes["connection"] = connection
    action(config)


async def upgrade_to_head(conn: AsyncConnection, *, ini_path: Path | None = None) -> None:
    """`alembic upgrade head` на спільному з'єднанні (транзакція викликача)."""
    await conn.run_sync(_run_with_connection, lambda cfg: command.upgrade(cfg, "head"), ini_path)


async def downgrade_to_base(conn: AsyncConnection, *, ini_path: Path | None = None) -> None:
    """`alembic downgrade base` — лише dev/test (production forward-only)."""
    await conn.run_sync(_run_with_connection, lambda cfg: command.downgrade(cfg, "base"), ini_path)


async def check_no_drift(conn: AsyncConnection, *, ini_path: Path | None = None) -> list[str]:
    """`alembic check`: порожній список — без drift; інакше рядки з описом diff або причиною
    (БД не на head — теж проблема для `--check`)."""
    problems: list[str] = []

    def _check(cfg: Config) -> None:
        try:
            command.check(cfg)
        except AutogenerateDiffsDetected as exc:
            problems.append(str(exc))
        except CommandError as exc:  # напр. «Target database is not up to date.»
            problems.append(str(exc))

    await conn.run_sync(_run_with_connection, _check, ini_path)
    return problems


async def current_revision(conn: AsyncConnection) -> str | None:
    """Поточна ревізія з `alembic_version` (None — порожня БД)."""
    from alembic.runtime.migration import MigrationContext

    def _current(connection: Connection) -> str | None:
        return MigrationContext.configure(connection).get_current_revision()

    return await conn.run_sync(_current)
